export const INITCAR = 'initCar'
export const ADDGOODS = 'addGoods'
export const REDUCEGOODS = 'reduceGoods'
export const ICLASS = 'Iclass'
export const FCLASS = 'Fclass'
export const REMOVEGOODS = 'removeGoods'